name: Publicar Documentación de Laboratorio 02

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Process 'customer-app'
        run: |
          echo "Procesando el proyecto customer-app..."
          cd customer-app
          npm install && npm i -g @compodoc/compodoc
          npx @compodoc/compodoc -p tsconfig.json -d ../docs/customer-app

      - name: Process 'notifications'
        run: |
          echo "Procesando el proyecto notifications..."
          cd notifications
          npm install && npm i -g @compodoc/compodoc
          npx @compodoc/compodoc -p tsconfig.json -d ../docs/notifications

      - name: Create main index.html
        run: |
          echo '<!DOCTYPE html><html><head><title>Documentación Lab 02</title><style>body{font-family:sans-serif;}</style></head><body>' > docs/index.html
          echo '<h1>Laboratorio 02 - Patrones Estructurales</h1><ul>' >> docs/index.html
          echo '<li><a href="customer-app/">Documentación de Patrón Facade (CustomerApp)</a></li>' >> docs/index.html
          echo '<li><a href="notifications/">Documentación de Patrón Bridge (Notifications)</a></li>' >> docs/index.html
          echo '</ul></body></html>' >> docs/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        